version: '3.7'
services:
  vscode:
    build: .
    container_name: vscode
    user: root
    restart: always
    environment:
      - PASSWORD=1212312121
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../:/home/coder/project
      - ./.local:/home/coder/.local/share/code-server
    ports:
      - 8080:8080
